# Generated by Django 3.2 on 2021-04-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeanProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_dropclass',
            name='advisor_signature',
        ),
        migrations.RemoveField(
            model_name='add_dropclass',
            name='financial_aid_representative_signature',
        ),
        migrations.RemoveField(
            model_name='add_dropclass',
            name='student_signature',
        ),
        migrations.RemoveField(
            model_name='permittoregister',
            name='advisor_signature',
        ),
        migrations.RemoveField(
            model_name='permittoregister',
            name='dean_signature',
        ),
        migrations.RemoveField(
            model_name='permittoregister',
            name='student_signature',
        ),
        migrations.RemoveField(
            model_name='transcriptrequest',
            name='student_signature',
        ),
        migrations.RemoveField(
            model_name='uggraduation',
            name='student_signature',
        ),
    ]
