# Generated by Django 3.2 on 2021-04-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeanProject', '0002_auto_20210412_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeaudit',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
