# Generated by Django 3.1.3 on 2021-04-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeanProject', '0003_profile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permittoregister',
            options={'verbose_name': 'Permit to Register'},
        ),
    ]
