# Generated by Django 3.1.3 on 2021-04-12 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeanProject', '0004_auto_20210412_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_dropclass',
            options={'verbose_name': 'Add/Drop Class'},
        ),
        migrations.AlterModelOptions(
            name='degreeaudit',
            options={'verbose_name': 'Degree Audit'},
        ),
        migrations.AlterModelOptions(
            name='mastergraduation',
            options={'verbose_name': "Master's Graduation"},
        ),
        migrations.AlterModelOptions(
            name='transcriptrequest',
            options={'verbose_name': 'Transcript Request'},
        ),
        migrations.AlterModelOptions(
            name='uggraduation',
            options={'verbose_name': 'Undergraduate Graduation'},
        ),
    ]
