# Generated by Django 3.2 on 2021-04-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeanProject', '0005_auto_20210418_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_num',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
    ]
