# Generated by Django 3.1.3 on 2021-04-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('DeanProject', '0005_auto_20210412_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tech_id',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.CreateModel(
            name='ApprovedForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_number', models.CharField(max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
