# Generated by Django 3.1.3 on 2021-04-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeanProject', '0006_auto_20210413_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_dropclass',
            name='isApproved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='add_dropclass',
            name='isDenied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='add_dropclass',
            name='isPending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='degreeaudit',
            name='isApproved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='degreeaudit',
            name='isDenied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='degreeaudit',
            name='isPending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mastergraduation',
            name='isApproved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mastergraduation',
            name='isDenied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mastergraduation',
            name='isPending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permittoregister',
            name='isApproved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permittoregister',
            name='isDenied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permittoregister',
            name='isPending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transcriptrequest',
            name='isApproved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transcriptrequest',
            name='isDenied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transcriptrequest',
            name='isPending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uggraduation',
            name='isApproved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uggraduation',
            name='isDenied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uggraduation',
            name='isPending',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ApprovedForms',
        ),
    ]
