# Generated by Django 3.1.3 on 2021-04-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeanProject', '0007_auto_20210413_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_dropclass',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='degreeaudit',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mastergraduation',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permittoregister',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transcriptrequest',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uggraduation',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
