# Generated by Django 3.2 on 2021-04-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeanProject', '0010_auto_20210418_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_num3B',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
