# Generated by Django 3.2 on 2021-04-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeanProject', '0011_alter_degreeauditamendmentrequest_atu_course_num3b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_subject',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='semester_taken',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
