# Generated by Django 3.2 on 2021-04-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeanProject', '0012_auto_20210418_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeauditamendmentrequest',
            name='semester_taken2B',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='degreeauditamendmentrequest',
            name='semester_taken3B',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
