# Generated by Django 3.2 on 2021-04-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeanProject', '0013_auto_20210419_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='semester_taken2B',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='semester_taken3B',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
