# Generated by Django 3.2 on 2021-04-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeanProject', '0014_auto_20210419_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_num',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_num1B',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_num2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_num2B',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_num3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_num3B',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_num4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_num5',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_number1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_number2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_number3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_number4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_number5',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_number6',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='course_num',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='course_num2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='course_num3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='course_num4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='course_num5',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='grade',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='semester_taken',
            field=models.CharField(max_length=50),
        ),
    ]
