# Generated by Django 3.2 on 2021-04-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeanProject', '0015_auto_20210419_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='grade',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
