# Generated by Django 3.2 on 2021-04-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeanProject', '0016_alter_degreeauditamendmentrequest_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='atu_course_subject',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='degreeauditamendmentrequest',
            name='semester_taken',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
